INSERT INTO proceso VALUES  (1,"Abastecimiento");
INSERT INTO proceso VALUES  (2,"Calidad");
INSERT INTO proceso VALUES  (3,"Comercial");
INSERT INTO proceso VALUES  (4,"Comercio Exterior");
INSERT INTO proceso VALUES  (5,"Compras");
INSERT INTO proceso VALUES  (6,"Contabilidad Y Financiera");
INSERT INTO proceso VALUES  (7,"Corte Motos");
INSERT INTO proceso VALUES  (8,"Corte Pol. Motos");
INSERT INTO proceso VALUES  (9,"Costura Pol.Motos");
INSERT INTO proceso VALUES  (10,"Direccion Sistemas De Gestion");
INSERT INTO proceso VALUES  (11,"Diseño Y Manufactura General");
INSERT INTO proceso VALUES  (12,"Ensamble Motos");
INSERT INTO proceso VALUES  (13,"Ensamble Pol. Empaque");
INSERT INTO proceso VALUES  (14,"Ensamble Pol. Motos");
INSERT INTO proceso VALUES  (15,"Ensamble Reposicion Vehículos");
INSERT INTO proceso VALUES  (16,"Gestion Humana");
INSERT INTO proceso VALUES  (17,"Gestion TI");
INSERT INTO proceso VALUES  (18,"Gestión TI");
INSERT INTO proceso VALUES  (19,"Gestion TIC");
INSERT INTO proceso VALUES  (20,"Inyeccion Pol. Motos");
INSERT INTO proceso VALUES  (21,"Logistica");
INSERT INTO proceso VALUES  (22,"Logistica ");
INSERT INTO proceso VALUES  (23,"Logistica Metalmecanica Reposicion");
INSERT INTO proceso VALUES  (24,"Mantenimiento");
INSERT INTO proceso VALUES  (25,"Manteniminto sin Asignar");
INSERT INTO proceso VALUES  (26,"Metalmecanica Desarrollo");
INSERT INTO proceso VALUES  (27,"Metalmecanica Indirectos");
INSERT INTO proceso VALUES  (28,"Metalmecanica Indirectos Calidad");
INSERT INTO proceso VALUES  (29,"Metalmecanica Indirectos Sin Asignar");
INSERT INTO proceso VALUES  (30,"Metalmecanica Motos");
INSERT INTO proceso VALUES  (31,"Metalmecanica Motos Calidad");
INSERT INTO proceso VALUES  (32,"Metalmecanica Prexa Indirectos");
INSERT INTO proceso VALUES  (33,"Metalmecanica Reposición Vehículos");
INSERT INTO proceso VALUES  (34,"Metalmecanica Reposición Vehículos Calidad");
INSERT INTO proceso VALUES  (35,"Metalmecanica Reposición Vehículos Logistica");
INSERT INTO proceso VALUES  (36,"Metalmecanica Sin Asignar Herramentales");
INSERT INTO proceso VALUES  (37,"Metalmecanica Vehículos");
INSERT INTO proceso VALUES  (38,"Motos");
INSERT INTO proceso VALUES  (39,"Pintura Motos");
INSERT INTO proceso VALUES  (40,"Poliuretano Indirectos Sin Asignar Herramentales");
INSERT INTO proceso VALUES  (41,"Poliuretano Motos");
INSERT INTO proceso VALUES  (42,"Poliuretano Motos Calidad");
INSERT INTO proceso VALUES  (43,"Poliuretano Motos Logistica");
INSERT INTO proceso VALUES  (44,"Practicante Produccion");
INSERT INTO proceso VALUES  (45,"Producción");
INSERT INTO proceso VALUES  (46,"Seguridad Industrial");
INSERT INTO proceso VALUES  (47,"Sgi");
INSERT INTO proceso VALUES  (48,"Subensamble Motos");
INSERT INTO proceso VALUES  (49,"Subensamble Pol. Motos");
INSERT INTO proceso VALUES  (50,"Subensamble Vehículos");
INSERT INTO proceso VALUES  (51,"Tuberia Motos");
INSERT INTO proceso VALUES  (52,"Tuberia Vehículos");
INSERT INTO proceso VALUES  (53,"Ventas Metalmecanica Vehículos");
