INSERT INTO rutas VALUES (1, 'RUTA 1 -ESTRELLA SUR');
INSERT INTO rutas VALUES (2, 'RUTA 1-SALIDA CALDAS');
INSERT INTO rutas VALUES (3, 'RUTA 2-SALIDA P. ENVIGADO');
INSERT INTO rutas VALUES (4, 'RUTA 3- SALIDA NIQUIA');